### ISSUE TITLE
Magically detect shell scripts

### ISSUE THREAD

**Issue by BaxterStockman** [infertux/bashcov#18]
Right now, Bashcov detects shell scripts by searching the project root for files ending with the extension `.sh`.  There are a [couple](https://github.com/minad/mimemagic) [of](https://github.com/blackwinter/ruby-filemagic) gems that interface with [libmagic](http://linux.die.net/man/3/libmagic) to provide MIME type identification of files based on reading some of their contents.  While it wouldn't be nice to _mandate_ the use of one or the other of those gems, we could selectively load them if present on the user's system, falling back to extension-based detection when neither gem is available.  What do you think, @infertux -- worth the effort?

**Comment by infertux** [comment]
I can't recall anybody asking or complaining about this. I'd rank it as "nice to have" - if you're keen to work on it, feel free to go ahead but otherwise I think it's fine to keep it in the issue tracker until it gets more attention.

Regarding the implementation, I agree we shouldn't mandate the use of another Gem. I'm thinking we could also use the `file` command but it'll have terrible performance if there are many files to scan through. Using `libmagic` sounds like a better idea.

**Comment by infertux** [comment]
Bumping priority on this as it impacted someone in #27. At first glance, the `ruby-filemagic` Gem seems more maintained and wouldn't add any new dependencies so I'm thinking we could maybe add it as a mandatory dependency to Bashcov. We'd need to scan for files with the MIME type `text/x-shellscript` and exclude any binary files. Thoughts @BaxterStockman?

**Comment by BaxterStockman** [comment]
Sounds good to me!  OTOH I think it should be fairly straightforward to code up an abstraction layer over multiple shell-script-identifying "backends" -- `ruby-filemagic`, `mimemagic`, the `file` executable, and filename extension matching -- which might be nice for folks who can't install a C compiler, `libmagic`, etc.  Admittedly, that's a pretty small audience.

**Comment by BaxterStockman** [comment]
@infertux -- I've started work on this; should have a changeset ready within a few days.
